apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap/app-config.yaml
- secret/app-secrets.yaml
- app/deployment.yaml
- service/service.yaml

commonLabels:
  project: weather-bot
  version: v1.0.0
